version: '3.4'

services:

  frontend:
    restart: always
    volumes:
      - /var/transcribe/certs/transcribe.crt:/etc/pki/tls/certs/localhost.crt
      - /var/transcribe/certs/transcribe.key:/etc/pki/tls/private/localhost.key
 
  api:
    restart: always
    volumes:
      - /var/transcribe/transcriptions:/transcriptions

  folderwatcher:
    restart: always
    volumes:
      - /var/transcribe/transcriptions:/appdata

  transcribe-SV:
     restart: always
     env_file:
        - /var/transcribe/secret/env-speech-key.txt

  transcribe-EN:
     restart: always
     env_file:
        - /var/transcribe/secret/env-speech-key.txt
