#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM msftspeech/spx:1.40.0 AS base
# Install .NET
COPY FolderWatcher/dotnet.tar.gz .
RUN mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY *.sln .
COPY docker-compose.dcproj .
COPY API/*.csproj ./API/
COPY Common/*.csproj ./Common/
COPY FolderWatcher/*.csproj ./FolderWatcher/
RUN dotnet restore Transcribe.sln
COPY API/* ./API/
COPY FolderWatcher/* ./FolderWatcher/
COPY Common/* ./Common/
WORKDIR "/src/."
RUN dotnet build "Transcribe.sln" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FolderWatcher/FolderWatcher.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FolderWatcher.dll"]