version: '3.4'

services:

  frontend:
    image: frontend
    volumes:
      - ./reactapp/.aspnet/https/reactapp.pem:/etc/pki/tls/certs/localhost.crt
      - ./reactapp/.aspnet/https/reactapp.key:/etc/pki/tls/private/localhost.key
      - ./reactapp/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4173:4173"
    build:
      context: ./reactapp/
      dockerfile: Dockerfile
    depends_on:
      - api

  api:
    image: api
    volumes:
       - ./Testdata/Data:/transcriptions # Volume where transcription data and metadata is stored
    environment:
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: Dockerfile.API
    depends_on:
      - folderwatcher

  folderwatcher:
    image: folderwatcher
    volumes:
       - "./Testdata/Data:/appdata"
    build:
      context: .
      dockerfile: Dockerfile.FolderWatcher 
    depends_on:
      - transcribe-SV
      - transcribe-EN
 

  transcribe-SV:
    container_name: transcribeSV
    image: mcr.microsoft.com/azure-cognitive-services/speechservices/speech-to-text:4.8.0-amd64-sv-se
    environment:
        - Eula=accept
        - Billing=https://swedencentral.api.cognitive.microsoft.com/sts/v1.0/issuetoken
    env_file:
        - ./env-speech-key.txt
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8g

  transcribe-EN:
    container_name: transcribeEN
    image: mcr.microsoft.com/azure-cognitive-services/speechservices/speech-to-text:4.8.0-amd64-en-us
    environment:
        - Eula=accept
        - Billing=https://swedencentral.api.cognitive.microsoft.com/sts/v1.0/issuetoken
    env_file:
        - ./env-speech-key.txt
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8g
