apiVersion: v1
kind: Service
metadata:
  name: svc-prd-api
  namespace: ns-prd-transcribe
  labels:
    app: transcribe-api
spec:
  type: ClusterIP
  selector:
    app: transcribe-api
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
  - port: 80
    targetPort: 80
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: svc-prd-frontend
  namespace: ns-prd-transcribe
  labels:
    app: transcribe-frontend
spec:
  type: ClusterIP
  selector:
    app: transcribe-frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-prd-transcribe
  namespace: ns-prd-transcribe 
spec:
  tls:
  - hosts:
    - frontend.example.com
    secretName: frontend-tls
  - hosts:
    - api.example.com
    secretName: api-tls
  rules:
  - host: frontend.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-prd-frontend
            port:
              number: 80
  - host: api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-prd-api
            port:
              number: 80
