namespace: ns-transcribe

# Values that requires configuration
required:
  frontend:
    ingress:
      hostname: "<frontend-hostname>"
    deployment:
      env:
        VITE_API_ENDPOINT: "<api-endpoint>"
        VITE_AUTH_CLIENTID: "<auth-clientid>"
        VITE_AUTH_APPID: "<auth-appid>"
        VITE_AUTH_TENANTID: "<auth-tenantid>"
        VITE_AUTH_REDIRECT_URL: "<auth-redirect-url>"
        VITE_AUTH_API_SCOPE: "<auth-api-scope>"
        VITE_REFRESH_INTERVAL_MS: "5000"
        VITE_APP_TITLE: "Transcribe"
  api:
    ingress:
      hostname: "<api-hostname>"
  tw:
    deployment:
      env:
        ITCF_TRANSCRIPTION_SCRIPT_START: "Transcriptionworker.ps1"
        ITCF_TRANSCRIPTION_SCRIPT_ERRORACTION: "Stop" # Change to "Continue" if you want the transcription worker to continue on error
    secrets:
      transcriptionWorkerApiKey: "<Base64 encoded API Key>"
  speechToText:
    deployment:
      env:
        Eula: "accept"
        Billing: "<Billing endpoint>"
      se:
        port: 5000


# Values that are default and should only be changed if you know what you are doing

persistentVolume:
  name: ps-transcribe
  storage: 50Gi

persistentVolumeClaim:
  name: pvc-transcribe
  storage: 50Gi

services:
  api:
    port: 443
    targetPort: 443
  frontend:
    port: 443
    targetPort: 443

deployments:
  frontend:
    image: "<frontend-image>"
    cpuLimit: "500m"
    memoryLimit: "1Gi"
  api:
    image: "<api-image>"
    cpuLimit: "500m"
    memoryLimit: "1Gi"
  tw:
    image: "<transcription-worker-image>"
    cpuLimit: "4000m"
    memoryLimit: "4Gi"
    env:
      ITCF_TRANSCRIPTION_SCRIPT_START: "Transcriptionworker.ps1"
  speechToText:
    image: "<speech-to-text-image>"
    cpuLimit: "4000m"
    memoryLimit: "4Gi"




