apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-transcribe
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.required.frontend.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-transcribe-frontend
            port:
              number: {{ .Values.services.frontend.port }}
  - host: {{ .Values.required.api.ingress.hostname }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: svc-transcribe-api
            port:
              number: {{ .Values.services.api.port }}
