apiVersion: v1
kind: Secret
metadata:
  name: secrets-transcribe-tw
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  az-cs-speech-to-text_api-key: {{ .Values.required.tw.secrets.transcriptionWorkerApiKey }}
