---
# Service for API
apiVersion: v1
kind: Service
metadata:
  name: svc-transcribe-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.services.api.port }}
      targetPort: {{ .Values.services.api.targetPort }}

---

# Service for Frontend
apiVersion: v1
kind: Service
metadata:
  name: svc-transcribe-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.services.frontend.targetPort }}
